version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 13.4.1
    environment:
      FL_OUTPUT_DIR: output
    working_directory: ~/build-env
    steps:
      - attach_workspace:
          at: ~/build-env
      - run:
          name: Symlink python
          command: ln -s /usr/local/bin/python3.9 /usr/local/bin/python
      - run:
          name: Check python version
          command: python -V
      - run:
          name: List Directories
          command: ls

workflows:
  build-test-lint:
    jobs:
      - build-and-test